backend:
  name: git-gateway
  branch: master

media_folder: "/src/pages/blog/img"
public_folder: "img"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Path", name: "path", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "relation", collection: "authors", searchFields: ["authorName"], valueField: "authorName", required: false}
      - {label: "Author Image", name: "authorImage", widget: "relation", collection: "authors", searchFields: ["authorName"], valueField: "authorImage", required: false}
      - {label: "Author Twitter Handle", name: "authorTwitter", widget: "relation", collection: "authors", searchFields: ["authorName"], valueField: "twitterHandle", required: false} 
      - {label: "Featured Image", name: "featuredImage", widget: "string", required: false}
      - {label: "Card Image", name: "image", widget: "image", required: false}
      - {label: "Featured Video", name: "featuredVideo", widget: "string", required: false}
      - {label: "Tags", name: tags, widget: list, required: false}
      - {label: "Unreal Version", name: uev, widget: string, required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "authors"
    label: "Authors"
    folder: "src/pages/authors"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Path", name: "path", widget: "string"}
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
      - {label: "Author Name", name: "authorName", widget: "string", required: false}
      - {label: "Author Image", name: "authorImage", widget: "string", required: false}
      - {label: "Twitter Handle", name: "twitterHandle", widget: "string", required: false}
      - {label: "Github Profile", name: "githubProfile", widget: "string", required: false}
      - {label: "Webiste", name: "authorWebsite", widget: "string", required: false}
      - {label: "Bio", name: "bio", widget: "text", required: false}

  - name: "about"
    label: "About"
    folder: "src/pages/about"
    create: false
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
      - {label: "Path", name: "path", widget: "hidden", default: "/about"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
